TARGET = servo

ARDUINO_DIR = ../arduino
AVRDUDE_CONF = /etc/avrdude.conf
AVRDUDE_ARD_PROGRAMMER = arduino
MCU = atmega328p
F_CPU = 16000000
ARDUINO_PORT = /dev/ttyACM0
AVRDUDE_ARD_BAUDRATE = 115200

ARDUINO_LIBS = Servo
ARDUINO_LIBS += Ethernet

include ../arduino-mk/Arduino.mk
