TARGET = servo

ARDUINO_DIR = /home/colin/bin/arduino-0022
AVRDUDE_CONF = /etc/avrdude.conf
AVR_TOOLS_PATH = /usr/bin
AVRDUDE_ARD_PROGRAMMER = arduino
MCU = atmega328p
F_CPU = 16000000
ARDUINO_PORT = /dev/ttyACM0
AVRDUDE_ARD_BAUDRATE = 115200

ARDUINO_LIBS = Servo
ARDUINO_LIBS += Ethernet

include ../arduino-mk/Arduino.mk
